# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [kik, Deer, Hunter, wolf,]
patreon: # Replace with a single Patreon username https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective username https://app.asana.com/0/1149860066242772/1149860066242772
ko_fi: # Replace with a single Ko-fi username Turbo87
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel -runtime
community_bridge: # Replace with a single Community Bridge project-name e.g., better mens project
liberapay: # Replace with a single Liberapay username Fan35
issuehunt: # Replace with a single IssueHunt username April
otechie: # Replace with a single Otechie username Emily
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://ultra.com', 'https://https://drive.google.com/file/d/1u8iDpYw3lf26XHat44ZSKyDdiF9Xz2pG/view?usp=drivesdk']
Https://wafflehouse.com
https://podcasts.apple.com/us/podcast/dolly-partons-america/id1481398762
https://en.wikipedia.org/wiki/Schizophrenia
Https://wish.com
Https://bigspot.com
